### ISSUE TITLE
Any update to this theme?

### ISSUE THREAD

**Issue by chilman408** [Chronicmemecrafter/Black_TFT_Theme#1]
It seems like the newest firmware from BTT uses a few new resources (e.g. 100_mm.bmp, apply.bmp...) that doesn't show up in this current iteration.

**Comment by GarlckBread** [comment]
> It seems like the newest firmware from BTT uses a few new resources (e.g. 100_mm.bmp, apply.bmp...) that doesn't show up in this current iteration.

I’ll have a look at it and see what I can do. I’m not the original designer so I’ll have to make something work but I haven’t really been 3D printing much recently and it hasn’t been on my mind. Thanks for letting me know.

**Comment by chilman408** [comment]
Thanks so much...

**Comment by dmcleish91** [comment]
I have updated some files to better suit the current firmware of the tft35 and fixed some issues. I,E menu screen items not updating and print status screen not displaying any values.

[bmp.zip](https://github.com/Chronicmemecrafter/Black_TFT_Theme/files/6134830/bmp.zip)

**Comment by GarlckBread** [comment]
> I have updated some files to better suit the current firmware of the tft35 and fixed some issues. I,E menu screen items not updating and print status screen not displaying any values.
> 
> [bmp.zip](https://github.com/Chronicmemecrafter/Black_TFT_Theme/files/6134830/bmp.zip)

Thank you for the helping my lazy butt
